/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngoinhacafe.GUI.Page.Popup;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import ngoinhacafe.GUI.Page.Interface.ActionPerform;
import ngoinhacafe.GUI.Page.TableHandler;

/**
 *
 * @author Admin
 */
public class ChonKhachHangPopup extends javax.swing.JFrame implements ActionListener, ActionPerform {

    /**
     * Creates new form ChonKhachHangPopup
     */
    public ChonKhachHangPopup(javax.swing.JTextField txtKH) {
        initComponents();
        addActionPerform();
        
        setTitle("Chọn khách hàng");
        setVisible(true);
        WindowActions.WindowClosing(this);
        
        setResizable(false);
        setLocationRelativeTo(null);
        
        khTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tbHandler.addRowToTable(new Object[] {
            "KH001",
            "Nguyễn Văn A",
            "273 An Dương Vương, phường 3, quận 5, TP.HCM",
            "0123456789",
            "Đã kích hoạt"
        }, khTable);
        tbHandler.addRowToTable(new Object[] {
            "KH001",
            "Nguyễn Văn A",
            "273 An Dương Vương, phường 3, quận 5, TP.HCM",
            "0123456789",
            "Đã kích hoạt"
        }, khTable);
        tbHandler.addRowToTable(new Object[] {
            "KH001",
            "Nguyễn Văn A",
            "273 An Dương Vương, phường 3, quận 5, TP.HCM",
            "0123456789",
            "Đã kích hoạt"
        }, khTable);
        
        this.txtKH = txtKH;
    }

    @Override
    public void addActionPerform() {
        chonBtn.addActionListener(this);
        themBtn.addActionListener(this);
    }
    
    javax.swing.JTextField txtKH;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        khTableContainer = new javax.swing.JScrollPane();
        khTable = new javax.swing.JTable();
        timkiemContainer = new javax.swing.JPanel();
        timKiemTheo = new javax.swing.JComboBox<>();
        timKiem = new javax.swing.JTextField();
        timKiemBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        themBtn = new javax.swing.JButton();
        chonBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        khTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "Số điện thoại", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        khTableContainer.setViewportView(khTable);

        timkiemContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        timKiemTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "Số điện thoại" }));

        timKiemBtn.setText("Tìm kiếm");

        javax.swing.GroupLayout timkiemContainerLayout = new javax.swing.GroupLayout(timkiemContainer);
        timkiemContainer.setLayout(timkiemContainerLayout);
        timkiemContainerLayout.setHorizontalGroup(
            timkiemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timKiemTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timKiemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        timkiemContainerLayout.setVerticalGroup(
            timkiemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timkiemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timKiemTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiemBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        themBtn.setText("Thêm mới");

        chonBtn.setText("Chọn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(themBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(chonBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themBtn)
                    .addComponent(chonBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(khTableContainer)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(timkiemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timkiemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(khTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chonBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable khTable;
    private javax.swing.JScrollPane khTableContainer;
    private javax.swing.JButton themBtn;
    private javax.swing.JTextField timKiem;
    private javax.swing.JButton timKiemBtn;
    private javax.swing.JComboBox<String> timKiemTheo;
    private javax.swing.JPanel timkiemContainer;
    // End of variables declaration//GEN-END:variables
    TableHandler tbHandler = new TableHandler();

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == chonBtn) {
            DefaultTableModel model = tbHandler.getTableModel(khTable);
            int selectedRow = khTable.getSelectedRow();
            
            if (khTable.getSelectedRow() == -1) {
                ThongBao.hienLoi("Vui lòng chọn khách hàng để thực hiện thao tác!");
            } else {
                String maKH = (String) model.getValueAt(selectedRow, 0);
            
                txtKH.setText(maKH);

                this.dispose();
            }
        }
        
        if (e.getSource() == themBtn) {
            new ThemSuaKhachHangPopup(txtKH);
            this.dispose();
        }
    }
}
