/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ngoinhacafe.GUI.Page;

/**
 *
 * @author ODL
 */
public class DashBoardForm extends javax.swing.JPanel {

    /**
     * Creates new form DashBoardForm
     */
    public DashBoardForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        plForm = new javax.swing.JPanel();
        lbHeader = new javax.swing.JLabel();
        plInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        plForm.setBackground(new java.awt.Color(254, 252, 243));
        plForm.setLayout(new java.awt.GridBagLayout());

        lbHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons8-coffee-shop-65.png"))); // NOI18N
        plForm.add(lbHeader, new java.awt.GridBagConstraints());

        plInput.setAlignmentX(2.0F);
        plInput.setAlignmentY(2.0F);
        plInput.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("id: 1");
        plInput.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Mật khẩu:");
        jLabel2.setPreferredSize(new java.awt.Dimension(41, 27));
        plInput.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("id: 1");
        plInput.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("id: 1");
        plInput.add(jLabel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 58, 0);
        plForm.add(plInput, gridBagConstraints);

        add(plForm, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JPanel plForm;
    private javax.swing.JPanel plInput;
    // End of variables declaration//GEN-END:variables
}
