/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ngoinhacafe.GUI.Page;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import ngoinhacafe.GUI.FormThemSua.ThemSuaKhuyenMaiForm;

/**
 *
 * @author ODL
 */
public class KhuyenMaiForm extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form KhuyenMaiForm
     */
    public KhuyenMaiForm() {
        initComponents();
        addActionPerform();
        kmTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void addActionPerform() {
        themBtn.addActionListener(this);
        suaBtn.addActionListener(this);
        xoaBtn.addActionListener(this);
    }
    
    public DefaultTableModel getTableModel() {
        return (DefaultTableModel) kmTable.getModel();
    }
    
    public void addRowToTable(Object[] data) {
        DefaultTableModel model = (DefaultTableModel) kmTable.getModel();
        
        model.addRow(data);
    }

    public void removeAllRow() {
        DefaultTableModel model = (DefaultTableModel) kmTable.getModel();
        
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        themBtn = new javax.swing.JButton();
        xoaBtn = new javax.swing.JButton();
        suaBtn = new javax.swing.JButton();
        kmTableContainer = new javax.swing.JScrollPane();
        kmTable = new javax.swing.JTable();
        timkiemContainer = new javax.swing.JPanel();
        timKiemTheo = new javax.swing.JComboBox<>();
        timKiem = new javax.swing.JTextField();
        timKiemBtn = new javax.swing.JButton();
        lamMoiBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 252, 243));

        themBtn.setText("Thêm");

        xoaBtn.setText("Xoá");

        suaBtn.setText("Sửa");

        kmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Điều kiện", "Giảm giá", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        kmTableContainer.setViewportView(kmTable);

        timkiemContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        timKiemTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã khuyến mãi", "Tên khuyến mãi", "Điều kiện khuyến mãi", "Phần trăm khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc" }));

        timKiemBtn.setText("Tìm kiếm");

        javax.swing.GroupLayout timkiemContainerLayout = new javax.swing.GroupLayout(timkiemContainer);
        timkiemContainer.setLayout(timkiemContainerLayout);
        timkiemContainerLayout.setHorizontalGroup(
            timkiemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timKiemTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timKiemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        timkiemContainerLayout.setVerticalGroup(
            timkiemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timkiemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timKiemTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiemBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lamMoiBtn.setText("Làm mới");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kmTableContainer)
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(timkiemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themBtn)
                .addGap(18, 18, 18)
                .addComponent(xoaBtn)
                .addGap(18, 18, 18)
                .addComponent(suaBtn)
                .addGap(18, 18, 18)
                .addComponent(lamMoiBtn)
                .addGap(399, 399, 399))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themBtn)
                    .addComponent(xoaBtn)
                    .addComponent(suaBtn)
                    .addComponent(lamMoiBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timkiemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kmTableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable kmTable;
    private javax.swing.JScrollPane kmTableContainer;
    private javax.swing.JButton lamMoiBtn;
    private javax.swing.JButton suaBtn;
    private javax.swing.JButton themBtn;
    private javax.swing.JTextField timKiem;
    private javax.swing.JButton timKiemBtn;
    private javax.swing.JComboBox<String> timKiemTheo;
    private javax.swing.JPanel timkiemContainer;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables

    ThemSuaKhuyenMaiForm fThemSua = null;
    @Override
    public void actionPerformed(ActionEvent e) {
        if (fThemSua != null)
            fThemSua.dispose();
        
        if (e.getSource() == themBtn) {
            fThemSua = new ThemSuaKhuyenMaiForm("Thêm", "");
        } else if (e.getSource() == lamMoiBtn) {
            
        } else if (e.getSource() == timKiemBtn) {
            String timKiemTheoTxt = (String) timKiemTheo.getSelectedItem();
            if (timKiemTheoTxt.equals("Tất cả")) {
                
            }
        } else if (kmTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khuyến mãi để thực hiện thao tác!");
            return;
        } else {
            DefaultTableModel model = getTableModel();
            int selectedRow = kmTable.getSelectedRow();
            
            String maKM = (String) model.getValueAt(selectedRow, 0);
            
            
            if (e.getSource() == suaBtn) {
                fThemSua = new ThemSuaKhuyenMaiForm("Sửa", maKM);
            }
            if (e.getSource() == xoaBtn) {
                int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá khuyến mãi này không?", "Xác nhận", JOptionPane.OK_CANCEL_OPTION);
                
                if (cf == JOptionPane.OK_OPTION) {
                    // Xác nhận xoá
                }
            }
        }
    }
}
