/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngoinhacafe.GUI.Page;

import ngoinhacafe.GUI.Page.MainForm;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import ngoinhacafe.GUI.ColorDesign;

/**
 *
 * @author DELL
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm2
     */
    public LoginForm() {
        initComponents();

        this.setTitle("Đăng nhập");
        ImageIcon logo = new ImageIcon(getClass().getResource("/assets/images/icons8-coffee-shop-65.png"));
        setIconImage(logo.getImage());

        this.setLocationRelativeTo(null);

        // add event Enter
        KeyAdapter enterLoginEvent = new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent ke) {
                if (ke.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnDangNhap.doClick();
                }
            }
        };
        txTenDangNhap.addKeyListener(enterLoginEvent);
        txTenDangNhap.addKeyListener(enterLoginEvent);
        // add auto select text on focus
        // https://stackoverflow.com/questions/7361291/select-all-on-focus-in-lots-of-jtextfield
        FocusListener autoSelectTextEvent = new FocusListener() {
            @Override
            public void focusGained(FocusEvent fe) {
                if (fe.getSource() instanceof JTextField) {
                    JTextField tx = (JTextField) fe.getSource();
                    tx.select(0, tx.getText().length());

                } else if (fe.getSource() instanceof JPasswordField) {
                    JPasswordField tx = (JPasswordField) fe.getSource();
                    tx.select(0, tx.getText().length());
                }

            }

            @Override
            public void focusLost(FocusEvent fe) {
                if (fe.getSource() instanceof JTextField) {
                    JTextField tx = (JTextField) fe.getSource();
                    tx.select(0, 0);

                } else if (fe.getSource() instanceof JPasswordField) {
                    JPasswordField tx = (JPasswordField) fe.getSource();
                    tx.select(0, 0);
                }
            }
        };
        txTenDangNhap.addFocusListener(autoSelectTextEvent);
        txTenDangNhap.addFocusListener(autoSelectTextEvent);

        // auto focus to tenDangNhap
        txTenDangNhap.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollBar1 = new javax.swing.JScrollBar();
        txMatKhau1 = new javax.swing.JPasswordField();
        plForm = new javax.swing.JPanel();
        lbHeader = new javax.swing.JLabel();
        plInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txTenDangNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txMatKhau = new javax.swing.JTextField();
        rbNhoMatKhau = new javax.swing.JRadioButton();
        btnDangNhap = new javax.swing.JButton();

        txMatKhau1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        plForm.setBackground(new java.awt.Color(254, 252, 243));
        plForm.setLayout(new java.awt.GridBagLayout());

        lbHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons8-coffee-shop-65.png"))); // NOI18N
        plForm.add(lbHeader, new java.awt.GridBagConstraints());

        plInput.setBackground(plForm.getBackground());
        plInput.setAlignmentX(2.0F);
        plInput.setAlignmentY(2.0F);
        plInput.setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        jLabel1.setBackground(plForm.getBackground());
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Tài khoản:");
        plInput.add(jLabel1);

        txTenDangNhap.setBackground(plForm.getBackground());
        txTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txTenDangNhap.setToolTipText("Nhập tài khoản");
        txTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTenDangNhapActionPerformed(evt);
            }
        });
        plInput.add(txTenDangNhap);

        jLabel2.setBackground(plForm.getBackground());
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Mật khẩu:");
        plInput.add(jLabel2);

        txMatKhau.setBackground(plForm.getBackground());
        txMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txMatKhau.setToolTipText("Nhập mật khẩu");
        txMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMatKhauActionPerformed(evt);
            }
        });
        plInput.add(txMatKhau);

        rbNhoMatKhau.setBackground(plForm.getBackground());
        rbNhoMatKhau.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rbNhoMatKhau.setText("Giữ đăng nhập");
        rbNhoMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNhoMatKhauActionPerformed(evt);
            }
        });
        plInput.add(rbNhoMatKhau);

        btnDangNhap.setBackground(new java.awt.Color(245, 235, 224));
        btnDangNhap.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        plInput.add(btnDangNhap);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 58, 0);
        plForm.add(plInput, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plForm, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plForm, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNhoMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNhoMatKhauActionPerformed

    }//GEN-LAST:event_rbNhoMatKhauActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String tentk = txTenDangNhap.getText();
        String mk = txTenDangNhap.getText();
        new MainForm().setVisible(true);
        //new FormChinh().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMatKhauActionPerformed

    private void txTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTenDangNhapActionPerformed

    public static String saveFileName = "temp";
//    public static Quyen quyenLogin;
//    public static NhanVien nhanVienLogin;
//    public static TaiKhoan taiKhoanLogin;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JPanel plForm;
    private javax.swing.JPanel plInput;
    private javax.swing.JRadioButton rbNhoMatKhau;
    private javax.swing.JTextField txMatKhau;
    private javax.swing.JPasswordField txMatKhau1;
    private javax.swing.JTextField txTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
